version: '3.7'

services:
  app:
    build: .
    container_name: email_app
    environment:
      - DB_HOST=postgres
      - DB_NAME=email_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    container_name: email_db
    image: postgres:latest
    environment:
      POSTGRES_DB: email_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: