version: '3.7'

services:
  app:
    build: .
    container_name: email_app
    environment:
      - DB_HOST=postgres
      - DB_NAME=email_db
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - postgres
      - ollama
    ports:
      - "8000:8000"
    networks:
      - infoscuolanet
    volumes:
      - ./src:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    container_name: email_db
    image: postgres:latest
    environment:
      POSTGRES_DB: email_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - infoscuolanet
    volumes:
      - pg_data:/var/lib/postgresql/data

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "7869:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=http://0.0.0.0:11434
    networks:
      - infoscuolanet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  pg_data:

networks:
    infoscuolanet:
        driver: bridge