version: "3.7"

services:
  app:
    build: .
    container_name: email_app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - OLLAMA_HOST=${OLLAMA_HOST}
      - IMAP_SERVER=${IMAP_SERVER}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      - PASSWORD=${PASSWORD}
      - RECIPIENTS=${RECIPIENTS}
    depends_on:
      - postgres
      - ollama
    ports:
      - "8000:8000"
    networks:
      - infoscuolanet
    volumes:
      - ./src:/app
    restart: unless-stopped
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    container_name: email_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - infoscuolanet
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=http://0.0.0.0:11434
    networks:
      - infoscuolanet
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  pg_data:

networks:
    infoscuolanet:
        driver: bridge
